update relatedLots field descriptions to neutral voice
open-contracting-extensions/ocds_lots_extension pull request #35
Opened 2022-04-06 14:54 UTC by odscjen

fixes https://github.com/open-contracting/ocds-extensions/issues/181

I haven't changed the description for `Tender.LotDetails` as I actually don't think it does need it. I've also not changed `Item.relatedLot` to `Item.relatedLots` as I realised unlike the others it's not an array and can only be a singular Lot.

2022-04-07 22:19 UTC, duncandewhurst requested changes

2022-04-07 22:19 UTC, duncandewhurst commented on README.md
> +* Update field descriptions to neutral voice
```suggestion
* Update field descriptions to use a neutral voice
```

2022-04-07 22:19 UTC, duncandewhurst commented on release-schema.json
> +          "title": "Related lot(s)",
```suggestion
          "title": "Related lot",
```

2022-04-07 22:23 UTC, duncandewhurst commented
> [](https://github.com/open-contracting/ocds-extensions/issues/181)
> 
> I haven't changed the description for `Tender.LotDetails` as I actually don't think it does need it.

`Tender.LotDetails` could be rewritten as:

> Details of any criteria that apply to bidding on the lots in this tender.

2022-04-11 01:49 UTC, duncandewhurst commented on release-schema.json
> +          "description": "Details of any criteria that apply to bidding on the lots in the tender",
```suggestion
          "description": "Details of any criteria that apply to bidding on the lots in this tender.",
```

2022-04-11 01:50 UTC, duncandewhurst approved these changes

2022-04-11 19:38 UTC, jpmckinney approved these changes

2022-04-11 19:38 UTC, merged