make Lot.id and LotGroup.id required, branched from master
open-contracting-extensions/ocds_lots_extension pull request #37
Opened 2022-04-11 09:25 UTC by odscjen

fixes https://github.com/open-contracting-extensions/ocds_lots_extension/pull/36 and partially addresses the issue in https://github.com/open-contracting/standard/issues/650

2022-04-12 00:13 UTC, duncandewhurst requested changes
You should be able to [resolve the merge conflict using the web editor](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

2022-04-12 00:13 UTC, duncandewhurst commented on README.md
> +* Make `Lot.id` and `LotGroup.id` required so that Lots and LotGroups are merged by identifier
```suggestion
* Make `Lot.id` and `LotGroup.id` required so that lots and lot groups are merged by identifier
```

2022-04-12 21:51 UTC, duncandewhurst approved these changes

2022-04-13 21:34 UTC, jpmckinney approved these changes

2022-04-13 21:34 UTC, merged